apiVersion: v1
kind: ReplicationController
metadata:
  name: myjava-rc
spec:
  replicas: 2
  selector:
    app: myjava
    version: 2.6.2
  template:
    metadata:
      labels:
        app: myjava
        version: 2.6.2
    spec:
      containers:
        - name: myjava-container
          image: umesh214/myjava:2
          ports:
            - containerPort: 8080
