apiVersion: v1
kind: ReplicationController
metadata:
  name: myonlinestore-rc
spec:
  replicas: 2
  selector:
    app: myonlinestore
    version: 2.6.1
  template:
    metadata:
      labels:
        app: myonlinestore
        version: 2.6.1
    spec:
      containers:
        - name: myonlinestore-container
          image: maha4iac/mahaonlinestrore:1
          ports:
            - containerPort: 8080
