apiVersion: v1
kind: ReplicationController
metadata:
  name: mahaonlinestore-rc
spec:
  replicas: 2
  selector:
    app: mahaonlinestore
    version: 2.6.1
  template:
    metadata:
      labels:
        app: mahaonlinestore
        version: 2.6.1
    spec:
      containers:
        - name: myjava-container
          image: maha4iac/mahaonlinestore:1
          ports:
            - containerPort: 8080
