apiVersion: v1
kind: Service
metadata:
  name: mahaonlinestore-svc
  labels:
    app: mahaonlinestore
    version: 2.6.2
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30002
    protocol: TCP
  selector:
    app: mahaonlinestore
    version: 2.6.2