apiVersion: v1
kind: Service
metadata:
  name: myonlinestore-svc
  labels:
    app: myonlinestore
    version: 2.6.1
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: myonlinestore
    version: 2.6.1